// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace CSharpQuery.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Search")]
    public partial class SearchFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Search.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Search", "In order to allow someone to find things\nAs the system\nI want to create a search " +
                    "index items use it to produce good search results", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Good search")]
        [NUnit.Framework.TestCaseAttribute("darren")]
        [NUnit.Framework.TestCaseAttribute("DARREN")]
        [NUnit.Framework.TestCaseAttribute("Darren")]
        [NUnit.Framework.TestCaseAttribute("Cauthon")]
        [NUnit.Framework.TestCaseAttribute("Darren Cauthon")]
        public virtual void GoodSearch(string searchTerm)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Good search", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "FirstName",
                        "LastName"});
            table1.AddRow(new string[] {
                        "4",
                        "Darren",
                        "Cauthon"});
#line 7
 testRunner.Given("I have the following people", ((string)(null)), table1);
#line 10
 testRunner.When("I index the people");
#line 11
 testRunner.And(string.Format("I search for \'{0}\'", searchTerm));
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key"});
            table2.AddRow(new string[] {
                        "4"});
#line 12
 testRunner.Then("my search results should include", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Bad search")]
        [NUnit.Framework.TestCaseAttribute("1234")]
        [NUnit.Framework.TestCaseAttribute("lskdflksjf")]
        [NUnit.Framework.TestCaseAttribute("Evan")]
        public virtual void BadSearch(string x)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Bad search", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "FirstName",
                        "LastName"});
            table3.AddRow(new string[] {
                        "4",
                        "Darren",
                        "Cauthon"});
#line 25
 testRunner.Given("I have the following people", ((string)(null)), table3);
#line 28
 testRunner.When("I index the people");
#line 29
 testRunner.And("I search for \'<search term>\'");
#line 30
 testRunner.Then("I should get no search results");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
